#Yaml for deploying the satisfactory server to a k8 cluster

# Creates the namespace satisfactory-server
apiVersion: v1
kind: Namespace
metadata:
  name: satisfactory-dedicated
---
#Create the PVC for satisfactory-data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-data
  namespace: satisfactory-dedicated
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
--- 
#Create the deployment for satisfactory
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-satisfactory-dedicated
  namespace: satisfactory-dedicated
spec:
  selector:
    matchLabels:
      app: server-satisfactory-dedicated
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server-satisfactory-dedicated
    spec:
      containers:
      - image: ghcr.io/william86370/satisfactory:main
        name: server-satisfactory-dedicated
        resources:
          requests:
            memory: "12G"
        ports:
          - name: server-15777
            containerPort: 15777
            protocol: UDP
          - name: server-15000
            containerPort: 15000
            protocol: UDP
          - name: server-7777
            containerPort: 7777
            protocol: UDP
        volumeMounts:
        - name: satisfactory-data
          mountPath: /Satisfactory-dedicated
      - name: browser
        image: filebrowser/filebrowser
        ports:
          - containerPort: 80
            name: http
        volumeMounts:
          - name: satisfactory-data
            mountPath: /srv
            subPath: "saves"
      volumes:
      - name: satisfactory-data
        persistentVolumeClaim:
          claimName: satisfactory-data
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: server-satisfactory-dedicated
  namespace: satisfactory-dedicated
spec:
  type: NodePort
  ports:
  - port: 15777
    nodePort: 30001
    name: server-15777
    protocol: UDP
  - port: 15000
    nodePort: 30002
    name: server-15000
    protocol: UDP
  - port: 7777
    nodePort: 30003
    name: server-7777
    protocol: UDP
  selector:
    app: server-satisfactory-dedicated
---
apiVersion: v1
kind: Service
metadata:
  namespace: satisfactory-dedicated
  name: satisfactory-browser-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: server-satisfactory-dedicated