apiVersion: v1
kind: Service
metadata:
  name: server-satisfactory-dedicated
spec:
  type: NodePort
  ports:
  - port: 15777
    nodePort: 30001
    name: server-15777
    protocol: UDP
  - port: 15000
    nodePort: 30002
    name: server-15000
    protocol: UDP
  - port: 7777
    nodePort: 30003
    name: server-7777
    protocol: UDP
  selector:
    app: server-satisfactory-dedicated
---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory-browser-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: server-satisfactory-dedicated